[2025-07-22T09:55:15.734+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_consumer_to_postgres.consume_kafka_store_postgres scheduled__2025-07-22T09:50:00+00:00 [queued]>
[2025-07-22T09:55:15.752+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_consumer_to_postgres.consume_kafka_store_postgres scheduled__2025-07-22T09:50:00+00:00 [queued]>
[2025-07-22T09:55:15.753+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-07-22T09:55:15.784+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): consume_kafka_store_postgres> on 2025-07-22 09:50:00+00:00
[2025-07-22T09:55:15.799+0000] {standard_task_runner.py:57} INFO - Started process 2145 to run task
[2025-07-22T09:55:15.808+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'kafka_consumer_to_postgres', 'consume_kafka_store_postgres', 'scheduled__2025-07-22T09:50:00+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/kafka_consumer_dag.py', '--cfg-path', '/tmp/tmp8ynlc_wo']
[2025-07-22T09:55:15.817+0000] {standard_task_runner.py:85} INFO - Job 51: Subtask consume_kafka_store_postgres
[2025-07-22T09:55:16.000+0000] {task_command.py:416} INFO - Running <TaskInstance: kafka_consumer_to_postgres.consume_kafka_store_postgres scheduled__2025-07-22T09:50:00+00:00 [running]> on host 539cb54e78a7
[2025-07-22T09:55:16.248+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_consumer_to_postgres' AIRFLOW_CTX_TASK_ID='consume_kafka_store_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-07-22T09:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-22T09:50:00+00:00'
[2025-07-22T09:55:16.297+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv4 ('192.168.65.254', 9092)]>: connecting to host.docker.internal:9092 [('192.168.65.254', 9092) IPv4]
[2025-07-22T09:55:16.578+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=host.docker.internal:9092 <checking_api_versions_recv> [IPv4 ('192.168.65.254', 9092)]>: Broker version identified as 2.6
[2025-07-22T09:55:16.579+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-2.2.15, node_id=bootstrap-0 host=host.docker.internal:9092 <connected> [IPv4 ('192.168.65.254', 9092)]>: Connection complete.
[2025-07-22T09:55:16.586+0000] {subscription_state.py:181} INFO - Updating subscribed topics to: ('patient_vitals',)
[2025-07-22T09:55:16.761+0000] {logging_mixin.py:154} INFO - Error in consume_and_store: connection to server at "host.docker.internal" (192.168.65.254), port 5432 failed: FATAL:  password authentication failed for user "postgres"
[2025-07-22T09:55:16.764+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/kafka_consumer_dag.py", line 19, in consume_and_store
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "host.docker.internal" (192.168.65.254), port 5432 failed: FATAL:  password authentication failed for user "postgres"

[2025-07-22T09:55:16.811+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=kafka_consumer_to_postgres, task_id=consume_kafka_store_postgres, execution_date=20250722T095000, start_date=20250722T095515, end_date=20250722T095516
[2025-07-22T09:55:16.848+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 51 for task consume_kafka_store_postgres (connection to server at "host.docker.internal" (192.168.65.254), port 5432 failed: FATAL:  password authentication failed for user "postgres"
; 2145)
[2025-07-22T09:55:16.914+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-07-22T09:55:16.970+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
